---
- include_tasks: packages.yml

  # Read Jitsi Meet config files and extract secrets for use in template configs.
  # Import to run these tasks after package installation, but before config tasks.
- include_tasks: dynamic_vars.yml

- include_tasks: prosody.yml

- include_tasks: jitsi_meet.yml

- include_tasks: jicofo.yml

- include_tasks: nginx.yml
  when: jitsi_meet_configure_nginx

- include_tasks: clean_up_default_configs.yml
  when: (jitsi_meet_ssl_cert_path != '' and
         jitsi_meet_ssl_key_path != '') or
         not jitsi_meet_configure_nginx


- include_tasks: ufw.yml
  when: jitsi_meet_configure_firewall == true

  # Placing the browser extensions last so the associated debugging tasks
  # that display URLs are visible near the end of the play.
- include_tasks: browser_extensions.yml
