# file: postgresql/tasks/main.yml

- include_tasks: install.yml
  tags: [postgresql, postgresql-install]

- include_tasks: extensions.yml
  tags: [postgresql, postgresql-extensions]

- include_tasks: configure.yml
  tags: [postgresql, postgresql-configure]

- include_tasks: databases.yml
  tags: [postgresql, postgresql-databases]

- include_tasks: users.yml
  tags: [postgresql, postgresql-users]

- include_tasks: monit.yml
  when: monit_protection is defined and monit_protection == true
  tags: [postgresql, postgresql-monit]
