---

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

  # add the python sni support to legacy python installations
- include_tasks: python_sni.yml
  when: ansible_os_family == 'Debian'
    and ansible_python_version | version_compare('2.6.0', '>=')
    and ansible_python_version | version_compare('2.7.9', '<')

  # install additional ansible dependencies
- name: install ansible support packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_support_packages }}"

- name: create gitea group
  group:
    name: "{{ gitea_group }}"
    state: present

- name: create gitea user
  user:
    name: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    home: "{{ gitea_working_dir }}"
    comment: Gitea

- name: make sure the directory containing gitea binary exist
  file:
    path: "{{ gitea_bin | dirname }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0755
    recurse: yes

- name: download gitea binary
  get_url:
    url: "{{ gitea_download_url }}"
    dest: "{{ gitea_bin }}"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0755

- name: install gitea config file
  file: path=/usr/local/bin/custom/conf
    state=directory
    owner=root
    group=root
    mode=640

- name: install gitea config file
  template: src=gitea.app.ini.j2
    dest="/usr/local/bin/custom/conf/app.ini"
    owner=root group=root mode=640

- include_tasks: mysql.yml
- include_tasks: services.yml
