---
#     |          |
# ,---|,---.,---.|__/ ,---.,---.
# |   ||   ||    |  \ |---'|
# `---'`---'`---'`   ``---'`


- name: ensure docker-io not installed
  apt:
    name: docker.io
    state: absent

- name: add docker GPG key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add official docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: "installing docker-ce"
  apt:
    name: docker-ce
    state: latest
    autoremove: yes

  with_items:
    - docker-ce
