---

#             88
#             ""   ,d
#                  88
#  ,adPPYb,d8 88 MM88MMM ,adPPYba, ,adPPYYba,
# a8"    `Y88 88   88   a8P_____88 ""     `Y8
# 8b       88 88   88   8PP""""""" ,adPPPPP88
# "8a,   ,d88 88   88,  "8b,   ,aa 88,    ,88
#  `"YbbdP"Y8 88   "Y888 `"Ybbd8"' `"8bbdP"Y8
#  aa,    ,88
#   "Y8bbdP"


- name: install gitea systemd script
  template:
    src: "systemd/gitea.service.j2"
    dest: "/etc/systemd/system/gitea.service"
    owner: root
    group: root
    mode: 755

  tags:
    - systemd

  notify:
    - restart gitea


- name: create git user
  user:
    name: git
    shell: /bin/false
    state: present
    home: "{{ python_clinic_git_dir }}"

- name: set permissions on git dir
  shell: "chown -R git: {{ python_clinic_git_dir }}"
