---
# .   .     o          |         |    |
# |   |,---..,---.,---.|--- ,---.|    |
# |   ||   |||   |`---.|    ,---||    |
# `---'`   '``   '`---'`---'`---^`---'`---'


- name: "ensure undesired packages are not present"
  apt:
    name: "{{ item }}"
    state: absent
    autoremove: yes

  with_items:
    - upstart
    - firewalld

#
#      DEPENDENCIES
#

- name: "installing dependencies"
  apt:
    name: "{{ item }}"
    state: latest
    autoremove: yes
    update_cache: yes

  with_items:
    - ack-grep
    - apt-transport-https
    - aptitude
    - bash-completion
    - ca-certificates
    - cron
    - curl
    - git
    - htop
    - memcached
    - nginx-full
    - ntp
    - openssl
    - pkg-config
    - python-passlib
    - python-mysqldb
    - python3
    - python3-dev
    - python3-pip
    - redis-server
    - redis-tools
    - rng-tools
    - rsync
    - software-properties-common
    - telnet
    - tree
    - unrar
    - vim
    - wget
    - whois
    - zip
