---

- name: ensure home directories for system users
  file:
    state: "directory"
    path: "{{ item.get('home', '{}/home/{}'.format(python_clinic_private_dir, item['username'])) }}"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0750

  with_items: "{{ python_clinic_system_users }}"


- name: ensure system users
  user:
    state: "present"
    name: "{{ item.username }}"
    home: "{{ item.get('home', '{}/home/{}'.format(python_clinic_private_dir, item['username'])) }}"
    group: "{{ item.username }}"

  with_items: "{{ python_clinic_system_users }}"
