- name: "installing firewalld"
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600 autoremove=yes
  with_items:
    - firewalld


- name: apply firewall rules
  firewalld: "{{ item }}"
  with_items: "{{ firewall_rules }}"
